public class Menu {
    public static void main(String[] args) {
        MenuItem<MenuItem<MenuItem<MenuItem<MenuItem<String>>>>>mainMenu = new MenuItem<>("Google Slides");
        MenuItem<MenuItem<MenuItem<MenuItem<String>>>>mainRibbon = new MenuItem<>("Main Options");
        mainMenu.insert(mainRibbon);

        MenuItem<MenuItem<MenuItem<String>>>mainFile = new MenuItem<>("File");
        MenuItem<MenuItem<MenuItem<String>>>mainEdit = new MenuItem<>("Edit");
        MenuItem<MenuItem<MenuItem<String>>>mainView = new MenuItem<>("View");
        MenuItem<MenuItem<MenuItem<String>>>mainInsert = new MenuItem<>("Insert");
        MenuItem<MenuItem<MenuItem<String>>>mainFormat = new MenuItem<>("Format");
        MenuItem<MenuItem<MenuItem<String>>>mainSlide = new MenuItem<>("Slide");
        MenuItem<MenuItem<MenuItem<String>>>mainArrange = new MenuItem<>("Arrange");
        MenuItem<MenuItem<MenuItem<String>>>mainTools= new MenuItem<>("Tools");
        MenuItem<MenuItem<MenuItem<String>>>mainAddons = new MenuItem<>("Add-ons");
        MenuItem<MenuItem<MenuItem<String>>>mainHelp = new MenuItem<>("Help");
        mainRibbon.insert(mainFile);
        mainRibbon.insert(mainEdit);
        mainRibbon.insert(mainView);
        mainRibbon.insert(mainInsert);
        mainRibbon.insert(mainFormat);
        mainRibbon.insert(mainSlide);
        mainRibbon.insert(mainArrange);
        mainRibbon.insert(mainTools);
        mainRibbon.insert(mainAddons);
        mainRibbon.insert(mainHelp);
        MenuItem<MenuItem<String>>mainFileNew = new MenuItem<>("New");
        MenuItem<MenuItem<String>>mainFileOpen = new MenuItem<>("Open");
        MenuItem<MenuItem<String>>mainFileImportS = new MenuItem<>("Import Slides");
        MenuItem<MenuItem<String>>mainFileMakeC = new MenuItem<>("Make a Copy");
        MenuItem<MenuItem<String>>mainFileEmail = new MenuItem<>("Email");
        MenuItem<MenuItem<String>>mainFileDownload = new MenuItem<>("Download");
        MenuItem<MenuItem<String>>mainFileVersionH = new MenuItem<>("Version History");
        MenuItem<MenuItem<String>>mainFileRename = new MenuItem<>("Rename");
        MenuItem<MenuItem<String>>mainFileMove = new MenuItem<>("Move");
        MenuItem<MenuItem<String>>mainFileAdd = new MenuItem<>("Add shortcut to Drive");
        MenuItem<MenuItem<String>>mainFileMoveT = new MenuItem<>("Move to trash");
        MenuItem<MenuItem<String>>mainFilePub = new MenuItem<>("Publish to the web");
        MenuItem<MenuItem<String>>mainFileDoc = new MenuItem<>("Document details");
        MenuItem<MenuItem<String>>mainFileLang = new MenuItem<>("Language");
        MenuItem<MenuItem<String>>mainFilePageS = new MenuItem<>("Page setup");
        MenuItem<MenuItem<String>>mainFilePrintSP = new MenuItem<>("Print settings and preview");
        MenuItem<MenuItem<String>>mainFilePrint = new MenuItem<>("Print");
        mainFile.insert(mainFileNew);
        mainFile.insert(mainFileOpen);
        mainFile.insert(mainFileImportS);
        mainFile.insert(mainFileMakeC);
        mainFile.insert(mainFileEmail);
        mainFile.insert(mainFileDownload);
        mainFile.insert(mainFileVersionH);
        mainFile.insert(mainFileRename);
        mainFile.insert(mainFileMove);
        mainFile.insert(mainFileAdd);
        mainFile.insert(mainFileMoveT);
        mainFile.insert(mainFilePub);
        mainFile.insert(mainFileDoc);
        mainFile.insert(mainFileLang);
        mainFile.insert(mainFilePageS);
        mainFile.insert(mainFilePrintSP);
        mainFile.insert(mainFilePrint);
        MenuItem<String>mainFileNewPresent = new MenuItem<>("Presentation");
        MenuItem<String>mainFileNewFrom = new MenuItem<>("From template");
        MenuItem<String>mainFileNewDoc = new MenuItem<>("Document");
        MenuItem<String>mainFileNewSS = new MenuItem<>("Spreadsheet");
        MenuItem<String>mainFileNewF = new MenuItem<>("Form");
        MenuItem<String>mainFileNewD = new MenuItem<>("Drawing");
        mainFileNew.insert(mainFileNewPresent);
        mainFileNew.insert(mainFileNewFrom);
        mainFileNew.insert(mainFileNewDoc);
        mainFileNew.insert(mainFileNewSS);
        mainFileNew.insert(mainFileNewF);
        mainFileNew.insert(mainFileNewF);
        mainFileNew.insert(mainFileNewD);
        MenuItem<String>mainFileMakeCEP = new MenuItem<>("Entire Presentation");
        MenuItem<String>mainFileMakeCSS = new MenuItem<>("Selected Slides");
        mainFileMakeC.insert(mainFileMakeCEP);
        mainFileMakeC.insert(mainFileMakeCSS);
        MenuItem<String>mainFileEmailEF = new MenuItem<>("Email this File");
        mainFileEmail.insert(mainFileEmailEF);
        MenuItem<String>mainFileDownloadMP = new MenuItem<>("Microsoft Powerpoint");
        MenuItem<String>mainFileDownloadODP = new MenuItem<>("ODP Document");
        MenuItem<String>mainFileDownloadPDF = new MenuItem<>("PDF Document");
        MenuItem<String>mainFileDownloadPT = new MenuItem<>("Plain Text");
        MenuItem<String>mainFileDownloadJPEG = new MenuItem<>("JPEG image");
        MenuItem<String>mainFileDownloadPNG = new MenuItem<>("PNG image");
        MenuItem<String>mainFileDownloadSVG = new MenuItem<>("Scalable Vector Graphics");
        mainFileDownload.insert(mainFileDownloadMP);
        mainFileDownload.insert(mainFileDownloadODP);
        mainFileDownload.insert(mainFileDownloadPDF);
        mainFileDownload.insert(mainFileDownloadPT);
        mainFileDownload.insert(mainFileDownloadJPEG);
        mainFileDownload.insert(mainFileDownloadPNG);
        mainFileDownload.insert(mainFileDownloadSVG);
        MenuItem<String>mainFileVersionHNCV = new MenuItem<>("Name current version");
        MenuItem<String>mainFileVersionHSVH = new MenuItem<>("See version history");
        mainFileVersionH.insert(mainFileVersionHNCV);
        mainFileVersionH.insert(mainFileVersionHSVH);
        MenuItem<MenuItem<String>>mainEditU = new MenuItem<>("Undo");
        MenuItem<MenuItem<String>>mainEditR = new MenuItem<>("Redo");
        MenuItem<MenuItem<String>>mainEditC = new MenuItem<>("Cut");
        MenuItem<MenuItem<String>>mainEditCp = new MenuItem<>("Copy");
        MenuItem<MenuItem<String>>mainEditP = new MenuItem<>("Paste");
        MenuItem<MenuItem<String>>mainEditPWF = new MenuItem<>("Paste without formatting");
        MenuItem<MenuItem<String>>mainEditDel = new MenuItem<>("Delete");
        MenuItem<MenuItem<String>>mainEditDup = new MenuItem<>("Duplicate");
        MenuItem<MenuItem<String>>mainEditSA = new MenuItem<>("Select all");
        MenuItem<MenuItem<String>>mainEditFAR = new MenuItem<>("Find and replace");
        mainEdit.insert(mainEditU);
        mainEdit.insert(mainEditR);
        mainEdit.insert(mainEditC);
        mainEdit.insert(mainEditCp);
        mainEdit.insert(mainEditP);
        mainEdit.insert(mainEditPWF);
        mainEdit.insert(mainEditDel);
        mainEdit.insert(mainEditDup);
        mainEdit.insert(mainEditSA);
        mainEdit.insert(mainEditFAR);
        MenuItem<MenuItem<String>>mainViewP = new MenuItem<>("Present");
        MenuItem<MenuItem<String>>mainViewM = new MenuItem<>("Motion");
        MenuItem<MenuItem<String>>mainViewTB = new MenuItem<>("Theme builder");
        MenuItem<MenuItem<String>>mainViewGV = new MenuItem<>("Grid view");
        MenuItem<MenuItem<String>>mainViewZ = new MenuItem<>("Zoom");
        MenuItem<MenuItem<String>>mainViewSR = new MenuItem<>("Show ruler");
        MenuItem<MenuItem<String>>mainViewG = new MenuItem<>("Guides");
        MenuItem<MenuItem<String>>mainViewST = new MenuItem<>("Snap to");
        MenuItem<MenuItem<String>>mainViewSTN = new MenuItem<>("Show speaker notes");
        MenuItem<MenuItem<String>>mainViewFS = new MenuItem<>("Full screen");
        mainView.insert(mainViewP);
        mainView.insert(mainViewM);
        mainView.insert(mainViewTB);
        mainView.insert(mainViewGV);
        mainView.insert(mainViewZ);
        mainView.insert(mainViewSR);
        mainView.insert(mainViewG);
        mainView.insert(mainViewSTN);
        mainView.insert(mainViewFS);
        MenuItem<String>mainViewZF = new MenuItem<>("Fit");
        MenuItem<String>mainViewZ50 = new MenuItem<>("50%");
        MenuItem<String>mainViewZ100 = new MenuItem<>("100%");
        MenuItem<String>mainViewZ200 = new MenuItem<>("200%");
        MenuItem<String>mainViewZZI = new MenuItem<>("Zoom in");
        MenuItem<String>mainViewZZO = new MenuItem<>("Zoom out");
        mainViewZ.insert(mainViewZF);
        mainViewZ.insert(mainViewZ50);
        mainViewZ.insert(mainViewZ100);
        mainViewZ.insert(mainViewZ200);
        mainViewZ.insert(mainViewZZI);
        mainViewZ.insert(mainViewZZO);
        MenuItem<String>mainViewGSG = new MenuItem<>("Show guides");
        MenuItem<String>mainViewGAVG = new MenuItem<>("Add vertical guide");
        MenuItem<String>mainViewGAHG = new MenuItem<>("Add horizontal guide");
        MenuItem<String>mainViewGEG = new MenuItem<>("Edit guides");
        MenuItem<String>mainViewGCG = new MenuItem<>("Clear guides");
        mainViewG.insert(mainViewGSG);
        mainViewG.insert(mainViewGAVG);
        mainViewG.insert(mainViewGAHG);
        mainViewG.insert(mainViewGEG);
        mainViewG.insert(mainViewGCG);
        MenuItem<String>mainViewSTGR = new MenuItem<>("Grid");
        MenuItem<String>mainViewSTGU = new MenuItem<>("Guides");
        mainViewST.insert(mainViewSTGR);
        mainViewST.insert(mainViewSTGU);

        MenuItem<MenuItem<String>>mainInsertI = new MenuItem<>("Image");
        MenuItem<MenuItem<String>>mainInsertTB = new MenuItem<>("Text box");
        MenuItem<MenuItem<String>>mainInsertA = new MenuItem<>("Audio");
        MenuItem<MenuItem<String>>mainInsertV = new MenuItem<>("Video");
        MenuItem<MenuItem<String>>mainInsertS = new MenuItem<>("Shape");
        MenuItem<MenuItem<String>>mainInsertT = new MenuItem<>("Table");
        MenuItem<MenuItem<String>>mainInsertC = new MenuItem<>("Chart");
        MenuItem<MenuItem<String>>mainInsertD = new MenuItem<>("Diagram");
        MenuItem<MenuItem<String>>mainInsertWA = new MenuItem<>("Word art");
        MenuItem<MenuItem<String>>mainInsertL = new MenuItem<>("Line");
        MenuItem<MenuItem<String>>mainInsertSC = new MenuItem<>("Special Characters");
        MenuItem<MenuItem<String>>mainInsertAN = new MenuItem<>("Animation");
        MenuItem<MenuItem<String>>mainInsertLK = new MenuItem<>("Link");
        MenuItem<MenuItem<String>>mainInsertCM = new MenuItem<>("Comment");
        MenuItem<MenuItem<String>>mainInsertNS = new MenuItem<>("New Slide");
        MenuItem<MenuItem<String>>mainInsertSN = new MenuItem<>("Slide numbers");
        MenuItem<MenuItem<String>>mainInsertPH = new MenuItem<>("Placeholder");
        mainInsert.insert(mainInsertI);
        mainInsert.insert(mainInsertTB);
        mainInsert.insert(mainInsertA);
        mainInsert.insert(mainInsertV);
        mainInsert.insert(mainInsertS);
        mainInsert.insert(mainInsertT);
        mainInsert.insert(mainInsertC);
        mainInsert.insert(mainInsertD);
        mainInsert.insert(mainInsertWA);
        mainInsert.insert(mainInsertL);
        mainInsert.insert(mainInsertSC);
        mainInsert.insert(mainInsertAN);
        mainInsert.insert(mainInsertLK);
        mainInsert.insert(mainInsertCM);
        mainInsert.insert(mainInsertNS);
        mainInsert.insert(mainInsertSN);
        mainInsert.insert(mainInsertPH);
        MenuItem<String>mainInsertIUFC = new MenuItem<>("Upload from computer");
        MenuItem<String>mainInsertISTW = new MenuItem<>("Search the web");
        MenuItem<String>mainInsertID = new MenuItem<>("Drive");
        MenuItem<String>mainInsertIP = new MenuItem<>("Photos");
        MenuItem<String>mainInsertIBU = new MenuItem<>("By URL");
        MenuItem<String>mainInsertIC = new MenuItem<>("Camera");
        mainInsertI.insert(mainInsertIUFC);
        mainInsertI.insert(mainInsertISTW);
        mainInsertI.insert(mainInsertID);
        mainInsertI.insert(mainInsertIP);
        mainInsertI.insert(mainInsertIBU);
        mainInsertI.insert(mainInsertIC);
        MenuItem<String>mainInsertSS = new MenuItem<>("Shapes");
        MenuItem<String>mainInsertSA = new MenuItem<>("Arrows");
        MenuItem<String>mainInsertSCA = new MenuItem<>("Callouts");
        MenuItem<String>mainInsertSE = new MenuItem<>("Equation");
        mainInsertS.insert(mainInsertSS);
        mainInsertS.insert(mainInsertSA);
        mainInsertS.insert(mainInsertSCA);
        mainInsertS.insert(mainInsertSE);
        MenuItem<String>mainInsertCB = new MenuItem<>("Bar");
        MenuItem<String>mainInsertCC = new MenuItem<>("Column");
        MenuItem<String>mainInsertCL = new MenuItem<>("Line");
        MenuItem<String>mainInsertCP = new MenuItem<>("Pie");
        mainInsertC.insert(mainInsertCB);
        mainInsertC.insert(mainInsertCC);
        mainInsertC.insert(mainInsertCL);
        mainInsertC.insert(mainInsertCP);
        MenuItem<String>mainInsertLL = new MenuItem<>("Line");
        MenuItem<String>mainInsertLA = new MenuItem<>("Arrow");
        MenuItem<String>mainInsertLEC = new MenuItem<>("Elbow Connector");
        MenuItem<String>mainInsertLCC = new MenuItem<>("Curved Connector");
        MenuItem<String>mainInsertLC = new MenuItem<>("Curve");
        MenuItem<String>mainInsertLP = new MenuItem<>("Polyline");
        MenuItem<String>mainInsertLS = new MenuItem<>("Scribble");
        mainInsertL.insert(mainInsertLL);
        mainInsertL.insert(mainInsertLA);
        mainInsertL.insert(mainInsertLEC);
        mainInsertL.insert(mainInsertLCC);
        mainInsertL.insert(mainInsertLC);
        mainInsertL.insert(mainInsertLP);
        mainInsertL.insert(mainInsertLS);

        MenuItem<MenuItem<String>>mainFormatT = new MenuItem<>("Text");
        MenuItem<MenuItem<String>>mainFormatAaI = new MenuItem<>("Align and indent");
        MenuItem<MenuItem<String>>mainFormatLPS = new MenuItem<>("Line &  paragraph spacing");
        MenuItem<MenuItem<String>>mainFormatBN = new MenuItem<>("Bullet and numbering");
        MenuItem<MenuItem<String>>mainFormatTa = new MenuItem<>("Table");
        MenuItem<MenuItem<String>>mainFormatCF = new MenuItem<>("Clear formatting");
        MenuItem<MenuItem<String>>mainFormatBL = new MenuItem<>("Border and lines");
        MenuItem<MenuItem<String>>mainFormatFO = new MenuItem<>("Format options");
        MenuItem<MenuItem<String>>mainFormatI = new MenuItem<>("Image");
        mainFormat.insert(mainFormatT);
        mainFormat.insert(mainFormatAaI);
        mainFormat.insert(mainFormatLPS);
        mainFormat.insert(mainFormatBN);
        mainFormat.insert(mainFormatTa);
        mainFormat.insert(mainFormatCF);
        mainFormat.insert(mainFormatBL);
        mainFormat.insert(mainFormatFO);
        mainFormat.insert(mainFormatI);

        MenuItem<MenuItem<String>>mainSlideNS = new MenuItem<>("New slide");
        MenuItem<MenuItem<String>>mainSlideDS = new MenuItem<>("Duplicate slide");
        MenuItem<MenuItem<String>>mainSlideDelS = new MenuItem<>("Delete slide");
        MenuItem<MenuItem<String>>mainSlideSS = new MenuItem<>("Skip slide");
        MenuItem<MenuItem<String>>mainSlideMS = new MenuItem<>("Move slide");
        MenuItem<MenuItem<String>>mainSlideCB = new MenuItem<>("Change background");
        MenuItem<MenuItem<String>>mainSlideAL = new MenuItem<>("Apply layout");
        MenuItem<MenuItem<String>>mainSlideT = new MenuItem<>("Transition");
        MenuItem<MenuItem<String>>mainSlideET = new MenuItem<>("Edit theme");
        MenuItem<MenuItem<String>>mainSlideCT = new MenuItem<>(" Change theme");
        mainSlide.insert(mainSlideNS);
        mainSlide.insert(mainSlideDS);
        mainSlide.insert(mainSlideDelS);
        mainSlide.insert(mainSlideSS);
        mainSlide.insert(mainSlideMS);
        mainSlide.insert(mainSlideCB);
        mainSlide.insert(mainSlideAL);
        mainSlide.insert(mainSlideT);
        mainSlide.insert(mainSlideET);
        mainSlide.insert(mainSlideCT);

        MenuItem<MenuItem<String>>mainArrangeO = new MenuItem<>("Order");
        MenuItem<MenuItem<String>>mainArrangeA = new MenuItem<>("Align");
        MenuItem<MenuItem<String>>mainArrangeD = new MenuItem<>("Distribute");
        MenuItem<MenuItem<String>>mainArrangeCOP = new MenuItem<>("Centre on page");
        MenuItem<MenuItem<String>>mainArrangeR = new MenuItem<>("Rotate");
        MenuItem<MenuItem<String>>mainArrangeG = new MenuItem<>("Group");
        MenuItem<MenuItem<String>>mainArrangeU = new MenuItem<>("Ungroup");
        mainArrange.insert(mainArrangeO);
        mainArrange.insert(mainArrangeA);
        mainArrange.insert(mainArrangeD);
        mainArrange.insert(mainArrangeCOP);
        mainArrange.insert(mainArrangeR);
        mainArrange.insert(mainArrangeG);
        mainArrange.insert(mainArrangeU);

        MenuItem<MenuItem<String>>mainToolsSpell = new MenuItem<>("Spelling");
        MenuItem<MenuItem<String>>mainToolsE = new MenuItem<>("Explore");
        MenuItem<MenuItem<String>>mainToolsL = new MenuItem<>("Linked objects");
        MenuItem<MenuItem<String>>mainToolsD = new MenuItem<>("Dictionary");
        MenuItem<MenuItem<String>>mainToolsQA = new MenuItem<>("Q&A history");
        MenuItem<MenuItem<String>>mainToolsVTSN = new MenuItem<>("Voice type speaker notes");
        MenuItem<MenuItem<String>>mainToolsSE = new MenuItem<>("Script editor");
        MenuItem<MenuItem<String>>mainToolsP = new MenuItem<>("Preference");
        MenuItem<MenuItem<String>>mainToolsA = new MenuItem<>("Accessibility");
        mainTools.insert(mainToolsSpell);
        mainTools.insert(mainToolsE);
        mainTools.insert(mainToolsL);
        mainTools.insert(mainToolsD);
        mainTools.insert(mainToolsQA);
        mainTools.insert(mainToolsVTSN);
        mainTools.insert(mainToolsSE);
        mainTools.insert(mainToolsP);
        mainTools.insert(mainToolsA);
        MenuItem<String>mainToolsSpellSC = new MenuItem<>("Spell check");
        MenuItem<String>mainToolsSpellUE = new MenuItem<>("Underline errors");
        MenuItem<String>mainToolsSpellPD = new MenuItem<>("Personal dictionary");
        mainToolsSpell.insert(mainToolsSpellSC);
        mainToolsSpell.insert(mainToolsSpellUE);
        mainToolsSpell.insert(mainToolsSpellPD);


        MenuItem<MenuItem<String>>mainAddonsDA = new MenuItem<>("Document add-ons");
        MenuItem<MenuItem<String>>mainAddonsGA = new MenuItem<>("Get add-ons");
        MenuItem<MenuItem<String>>mainAddonsMA = new MenuItem<>("Manage add-ons");
        mainAddons.insert(mainAddonsDA);
        mainAddons.insert(mainAddonsGA);
        mainAddons.insert(mainAddonsMA);

        MenuItem<MenuItem<String>>mainHelpSH = new MenuItem<>("Slides Help");
        MenuItem<MenuItem<String>>mainHelpT = new MenuItem<>("Training");
        MenuItem<MenuItem<String>>mainHelpU = new MenuItem<>("Updates");
        MenuItem<MenuItem<String>>mainHelpHSI = new MenuItem<>("Help Slides Improve");
        MenuItem<MenuItem<String>>mainHelpRAC = new MenuItem<>("Report abuse/copyright");
        MenuItem<MenuItem<String>>mainHelpKS = new MenuItem<>("Keyboard shortcuts");
        mainHelp.insert(mainHelpSH);
        mainHelp.insert(mainHelpT);
        mainHelp.insert(mainHelpU);
        mainHelp.insert(mainHelpHSI);
        mainHelp.insert(mainHelpRAC);
        mainHelp.insert(mainHelpKS);

        /*  TO TEST PROGRAM:
            mainMenu.insert() to add every ribbon to the main menu
            mainMenu.navigate()
         */
    }

}
